###########################################################################################
#                                         WARNING                                         #
# THIS PLUGIN IS FOR MODERATELY ADVANCED USERS. FOR A SIMPLISTIC PLUGIN, SEE DISCORD SRV  #
# IF YOU MAKE A MISTAKE IN CONFIGURATION, WE WILL NOT BABY YOU THROUGH FIGURING IT OUT.   #
###########################################################################################

####################
#     Language     #
####################
lang: en

####################
#     Webhooks     #
####################
# Webhooks can only be used for relaying messages. They cannot be used to receive messages.
webhooks:

  # Whether or not webhooks should be enabled.
  enabled: true

  # A list of webhooks to send messages to.
  urls:
    - https://discord.com/webhook1

  # Whether or not to use the player's skin as the avatar for the webhook.
  use_avatar: true

  # The URL that should be used for providing the skins to the webhook for each user.
  # %uuid is replaced with the user's uuid.
  # %name is replaced with the user's name.
  skins_url: https://minotar.net/helm/%uuid/2048

###############
#     Bot     #
###############
# Bots can be used for both relaying and receiving messages.
# They can also be used to provide other information about the server in unique ways.
bot:

  # Whether or not the usage of a bot is enabled.
  # This value will not change until this server is restarted.
  enabled: true

  # Whether or not the bot should re-send edited Discord messages with an asterisk at the end.
  show_edits: true

  # The token of the bot that should be used.
  token: "INSERT_TOKEN_HERE"

  # A list of channel ids that should receive messages from the Minecraft server.
  # Leave blank to disable sending messages via the bot.
  receive_channels:
    - 000000000000000000

  # A list of channel ids that should send messages to the Minecraft server.
  # Leave blank to disable receiving messages via the bot. Useful if you want to use webhooks in combination with a bot.
  relay_channels:
    - 000000000000000000

  # Options related to the Discord server that become available when using a bot
  discord:

    # The prefix to use for Discord commands
    # Defaults to "tdl!" if null or blank
    prefix: "tdl!"

    # The different games / activities that the Discord bot can show
    activities:
      - "Minecraft"
      - "mywebsite.net"

    # The rate at which these statuses will cycle in seconds (minimum 15 seconds)
    activity_cycle_speed: 300

    # The commands to include on the Discord server that users can run.
    # To disable, just leave blank
    # Supports Placeholder API
    commands:
      ip: "Join us at `server.mywebsite.net`"
      website: "Visit our website at https://www.mywebsite.net/"

###########################
#     System Messages     #
###########################
# Messages that will send on the following events. Messages configurable in lang file.
# Set to false to disable the messages from sending.
events:
  server_start: true
  server_shutdown: true
  player_join: true
  player_quit: true
  player_death: true
  player_advance: true

###################
#     Tagging     #
###################
tagging:
  # Whether or not to filter out ANY phrases starting with @ (prevents any mentions in Discord).
  enable_tagging: true

  # Whether or not to filter out @here and @everyone.
  enable_everyone_tagging: false

  # Whether or not to filter out ANY phrases starting with @& (prevents role mentions in Discord.)
  enable_role_tagging: false

  # Whether or not to make a noise & show chat color when a Minecraft user's username is said in Discord.
  mention_minecraft_users: true

  # Don't change this unless you know exactly what it should be.
  mention_minecraft_noise: "ENTITY_EXPERIENCE_ORB_PICKUP"

  # Whether or not to identify any attempted tags (@Fire) and convert them into mentions on Discord.
  # Only works if a bot is enabled because it needs to be aware of what users there are in the Discord server.
  mention_discord_users: true

  # A list of guild ids to use the member lists from to check for mentions.
  mention_servers:
    - 000000000000000000