###########################################################################################
#                                         WARNING                                         #
# THIS PLUGIN IS FOR MODERATELY ADVANCED USERS. FOR A SIMPLISTIC PLUGIN, SEE DISCORD SRV  #
# IF YOU MAKE A MISTAKE IN CONFIGURATION, WE WILL NOT BABY YOU THROUGH FIGURING IT OUT.   #
###########################################################################################

####################
#     Language     #
####################
lang: en

####################
#     Webhooks     #
####################
# Webhooks can only be used for relaying messages. They cannot be used to receive messages.
webhooks:

  # Whether or not webhooks should be enabled.
  enabled: true

  # A list of webhooks to send messages to
  urls:
    - https://discord.com/webhook1

  # Whether or not to use the player's skin as the avatar for the webhook
  use_avatar: true

  # The URL that should be used for providing the skins to the webhook for each user.
  # %uuid is replaced with the user's uuid.
  skins_url: https://minotar.net/helm/%uuid/2048

###############
#     Bot     #
###############
# Bots can be used for both relaying and receiving messages.
# They can also be used to provide other information about the server in unique ways.
bot:

  # Whether or not the usage of a bot is enabled.
  # This value will not change until this server is restarted.
  enabled: true

  # The token of the bot that should be used
  token: "INSERT_TOKEN_HERE"

  # A list of channel ids that should receive messages from the Minecraft server.
  # Leave blank to disable sending messages via the bot.
  receive_channels:
    - 000000000000000000

  # A list of channel ids that should relay messages to the Minecraft server.
  # Leave blank to disable receiving messages via the bot. Useful if you want to use webhooks in combination with a bot.
  relay_channels:
    - 000000000000000000

###########################
#     System Messages     #
###########################
# Messages that will send on the following events. Messages configurable in lang file.
# Set to false to disable the messages from sending.
events:
  player_join: true
  player_quit: true
  player_death: true