# Run Information
api-version: "1.15"
main: com.firecontroller1847.truediscordlink.TrueDiscordLink
softdepend: [PlaceholderAPI, Essentials]
load: POSTWORLD

# Metadata Information
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: FireController#1847
website: https://www.visualfiredev.com/

# Commands
commands:
  truediscordlink:
    description: Lists all of the available commands for the plugin
    usage: /truediscordlink
    aliases: [truediscord,discordlink,discord,tdl]
    permission: truediscordlink.command.discord

# Permissions
permissions:
  # Stars
  truediscordlink.*:
    description: Gives permission to everything TrueDiscordLink
    default: op
    children:
      truediscordlink.command.*: true
      truediscordlink.tagging.*: true
  truediscordlink.command.*:
    description: Gives permission to all TrueDiscordLink commands
    default: op
    children:
      truediscordlink.command.discord: true
      truediscordlink.command.reload: true
      truediscordlink.command.link: true
      truediscordlink.command.unlink: true
      truediscordlink.command.relay: true
      truediscordlink.command.relaysilent: true
  truediscordlink.tagging.*:
    description: Gives permission to all TrueDiscordLink tagging features
    default: op
    children:
      truediscordlink.tagging.user: true
      truediscordlink.tagging.channel: true

  # Commands
  truediscordlink.command.discord:
    description: Gives permission to the main command
    default: true
  truediscordlink.command.reload:
    description: Gives permission to the reload command
    default: op
  truediscordlink.command.link:
    description: Gives permission to link a user account
    default: true
  truediscordlink.command.unlink:
    description: Gives permission to unlink a user account
    default: true
  truediscordlink.command.relay:
    description: Relays the given message to the Discord server
    default: op
  truediscordlink.command.relaysilent:
    description: Silently relays the given message to the Discord server
    default: op

  # Features
  truediscordlink.tagging.user:
    description: Gives permission to tag users in Discord
    default: true
  truediscordlink.tagging.channel:
    description: Gives permission to tag channels in Discord
    default: true